# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.1/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: clickstack-repo
  namespace: observability
spec:
  interval: 1m0s
  url: https://hyperdxio.github.io/helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
# https://artifacthub.io/packages/helm/hdx-oss-v2/clickstack
# https://github.com/hyperdxio/helm-charts/blob/main/charts/clickstack/values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickstack-release
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: clickstack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: clickstack-repo
      version: 1.0.0
  values:
    global:
      storageClassName: hcloud-volumes
    hyperdx:
      env:
        - name: BETA_CH_OTEL_JSON_SCHEMA_ENABLED
          value: "true"
      useExistingConfigSecret: true
      existingConfigSecret: hyperdx-external-config
      existingConfigConnectionsKey: connections.json
      existingConfigSourcesKey: sources.json
      otelExporterEndpoint: "http://otel-collector.observability.svc.cluster.local:4318"
      apiKey: 48daf6aa-a32e-4c36-afbb-4b5ffb5ec27f
    clickhouse:
      enabled: false
    otel:
      clickhouseEndpoint: "http://clickhouse-cluster01.clickhouse.svc.cluster.local:8123"
      clickhousePrometheusEndpoint: "clickhouse-operator-altinity-clickhouse-operator-metrics.clickhouse.svc.cluster.local:8888"
      clickhouseDatabase: otel
      clickhouseUser: otel-collector
      env:
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-opentelemetry-collector-account
              key: password
        - name: OTEL_AGENT_FEATURE_GATE_ARG
          value: "--feature-gates=clickhouse.json"
