# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.1/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: clickstack-repo
  namespace: observability
spec:
  interval: 1m0s
  url: https://hyperdxio.github.io/helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
# https://artifacthub.io/packages/helm/hdx-oss-v2/clickstack
# https://github.com/hyperdxio/helm-charts/blob/main/charts/clickstack/values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickstack-release
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: clickstack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: clickstack-repo
      version: 1.0.0
  values:
    global:
      storageClassName: hcloud-volumes
    hyperdx:
      env:
        - name: BETA_CH_OTEL_JSON_SCHEMA_ENABLED
          value: "true"
      useExistingConfigSecret: true
      existingConfigSecret: hyperdx-external-config
      existingConfigConnectionsKey: connections.json
      existingConfigSourcesKey: sources.json
      otelExporterEndpoint: "http://otel-collector.observability.svc.cluster.local:4318"
      apiKey: 48daf6aa-a32e-4c36-afbb-4b5ffb5ec27f
    clickhouse:
      enabled: false
    otel:
      clickhouseEndpoint: "http://clickhouse-cluster01.clickhouse.svc.cluster.local:8123"
      clickhousePrometheusEndpoint: "clickhouse-operator-altinity-clickhouse-operator-metrics.clickhouse.svc.cluster.local:8888"
      clickhouseDatabase: otel
      clickhouseUser: otel-collector
      env:
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-opentelemetry-collector-account
              key: password
        - name: OTEL_AGENT_FEATURE_GATE_ARG
          value: "--feature-gates=clickhouse.json"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry-repo
  namespace: observability
spec:
  interval: 1m0s
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
# https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-operator
# https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator-release
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: opentelemetry-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-repo
      version: 0.99.2
  values:
    manager:
      operator:
        targetallocator:
          mtls: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-targetallocator
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  - nonResourceURLs: ["/apis/*"]
    verbs: ["get"]
  - nonResourceURLs: ["/apis"]
    verbs: ["get"]
  - nonResourceURLs: ["/api/*"]
    verbs: ["get"]
  - nonResourceURLs: ["/api"]
    verbs: ["get"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
    verbs:
      - "*"
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificaterequests
      - certificates
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-targetallocator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-targetallocator
subjects:
  - kind: ServiceAccount
    name: agent-collector-targetallocator
    namespace: observability
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: agent-collector
  namespace: observability
spec:
  mode: daemonset
  targetAllocator:
    enabled: true
    allocationStrategy: per-node
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - 0.0.0.0:8888
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    exporters:
      otlp:
        endpoint: clickstack-release-otel-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [otlp]
# ---
# TODO: go autoinstrumentation (https://opentelemetry.io/docs/platforms/kubernetes/operator/automatic/#go)
# apiVersion: opentelemetry.io/v1alpha1
# kind: Instrumentation
# metadata:
#   name: otel-instrumentation
# spec:
#   exporter:
#     endpoint: http://agent-collector.observability.svc.cluster.local:4317
#   propagators:
#     - tracecontext
#     - baggage
#     - b3
#   go:
#     env:
#       # Required if endpoint is set to 4317.
#       # Go autoinstrumentation uses http/proto by default
#       # so data must be sent to 4318 instead of 4317.
#       - name: OTEL_EXPORTER_OTLP_ENDPOINT
#         value: http://agent-collector.observability.svc.cluster.local:4318
