# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.31.1/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-demo
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry-repo
  namespace: opentelemetry-demo
spec:
  interval: 1m0s
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-demo-release
  namespace: opentelemetry-demo
spec:
  interval: 10m
  chart:
    spec:
      chart: opentelemetry-demo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-telemetry-repo
      version: 0.38.6
  values:
    default:
      env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app.kubernetes.io/component']"
        - name: OTEL_COLLECTOR_NAME
          value: otel-collector.observability.svc.cluster.local
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: 'service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.1.3'
    components:
    opentelemetry-collector:
      enabled: false
    jaeger:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    opensearch:
      enabled: false
